### ISSUE TITLE
Allowing implicit aliasing of parameters (public comment c201412e00001)

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#1177]
The public comment [c201412e00001] (https://lists.oasis-open.org/archives/odata-comment/201412/msg00001.html) with title "Parameter implicit aliasing" suggests to add a short-hand notation for parameter aliases, e.g. 

GET http://<serviceroot>/Add()?a=1&b=1 

instead of the currently necessary

GET http://<serviceroot>/Add(a=@a,b=@b)?@a=1&@b=1.

### Proposal

Support only when the function/action is the last segment:

A service may support invoking a function as the last segment in a path by omitting the parens and supplying the named parameters as query options prefixed with the "@" sign ([ODATA-763](https://issues.oasis-open.org/browse/ODATA-763) and [ODATA-644](https://issues.oasis-open.org/browse/ODATA-644)). For maximum interoperability, services must continue to support the parens syntax as well.

Precedence rules apply for cases where the function name conflicts with a property name. In particular, the declared property wins over a function, and a function would win over a dynamic property.

Imported from [ODATA-763](https://issues.oasis-open.org/browse/ODATA-763)

**Comment by vmikhailenko** [comment]
Question: is the complex values e.g. json arrays or objects are permitted as values for implicit aliases? Are we right to assume that whatever is supported as value for an explicit alias (except the expression) can be supplied with an implicit one?

CC @HeikoTheissen

**Comment by HeikoTheissen** [comment]
> Question: are the complex values e.g. json arrays or objects are permitted as values for implicit aliases?

Yes.
