### ISSUE TITLE
CSDL: deprecate SRID value "variable"

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#1935]
With #456 we removed mention of the obsolete [GeoJSON-2008] document and the optional [CRS object](http://geojson.org/geojson-spec.html#named-crs).

This makes it non-obvious/impossible to serialize Geo values of properties with `SRID="variable"`.

### Proposal

CSDL
- Deprecate (or remove?) [SRID](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.02/csd01/odata-csdl-xml-v4.02-csd01.html#SRID) value `variable`
- Mention in "Changes" section

JSON Format
- Mention #456 in "Changes" section
- Refer to https://datatracker.ietf.org/doc/html/rfc7946#section-4 in paragraph about Geo serialization

**Comment by sthagen** [comment]
I think using CRS simply means, the payload is GeoJSON version 1 and not version 2, the RFC version. Some discussions of ours during development of the GeoJSON RFC

- [Mail-thread on that topic on the IETF GeoJSON mailing list "Re: [Geojson] GeoJSON 2.0"](https://mailarchive.ietf.org/arch/msg/geojson/oi5qiO-nuRoXL9K9b6OJHPpm-kY/)
- [The information around the pull request on that RFC draft for version 2 mentioned in the email thread on the rationale and the "safe/interoperable/tolerable" dimension of using a single CRS](https://github.com/geojson/draft-geojson/pull/202#issue-150992272)
- [Changes section in Sean's blog post on RFC 7946 publication](https://sgillies.net/2016/08/11/rfc-7946-the-geojson-format.html#changes)
- [\[Appendix B\].  Changes from the Pre-IETF GeoJSON Format Specification](https://datatracker.ietf.org/doc/html/rfc7946#appendix-B)
