### ISSUE TITLE
Clarify wording for error in processing delta update

### ISSUE THREAD

**Issue by mikepizzo** [oasis-tcs/odata-specs#1965]
In [OData Version 4.02. Part 1: Protocol (oasis-open.org)](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#UpdateaCollectionofEntities) we say:

> If the [continue-on-error](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#Preferencecontinueonerrorodatacontinueonerror) preference has been specified and any errors occur in processing the changes, then a delta response MUST be returned regardless of the [return](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#Preferencereturnrepresentationandreturnminimal) preference and MUST contain at least the failed changes.

Since continue-on-error is a preference, shouldn't the service be allowed to fail the request entirely (without applying any changes) and return an error, within the continue-on-error preferenceapplied set to false?

I *think* what we meant was that, if the continue-on-error preference is *honored* and errors occur then the response must be returned.

**Comment by ralfhandl** [comment]
Sounds reasonable
