### ISSUE TITLE
Batch requests: Referencing values from response bodies more generally

### ISSUE THREAD

**Issue by HeikoTheissen** [oasis-tcs/odata-specs#1969]
[OData-Protocol, section 11.7.6](https://oasis-tcs.github.io/odata-specs/odata-protocol/odata-protocol.html#ReferencingValuesfromResponseBodies) states:
> Alternatively, a value reference can consist of a $ character followed by the value of an instance annotation with term [Core.ContentID](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.md#ContentID) (see [OData-VocCore](https://oasis-tcs.github.io/odata-specs/odata-protocol/odata-protocol.html#ODataVocCore)) that occurs in the payload of the preceding request as described in [section 11.4.2.2](https://oasis-tcs.github.io/odata-specs/odata-protocol/odata-protocol.html#CreateRelatedEntitiesWhenCreatinganEntity) and [section 11.4.3.1](https://oasis-tcs.github.io/odata-specs/odata-protocol/odata-protocol.html#UpdateRelatedEntitiesWhenUpdatinganEntity), then the referenced value is the corresponding value in the response, which the service SHOULD annotate with the same Core.ContentID value.

This is too narrow. `Core.ContentID` instance annotations may also appear in responses to other types of request, for example, action invocations.

**Comment by ralfhandl** [comment]
TC 2024-08-28: for the existing cases (insert, update) the relationship between ContentIDs in request and response is "canonical". For actions this is less clear.

@HeikoTheissen to follow up on this relationship and reduce the amount of out-of-band knowledge.

@ralfhandl & @HeikoTheissen to find out which parts of content-id referencing are already implemented by SAP.

**Comment by ralfhandl** [comment]
TC agrees that the new functionality can be purely provided via vendor-specific extensions and no changes to the Core specifications are needed.
