### ISSUE TITLE
Add multipart batch example for "Referencing Returned Entities"

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#1976]
Add example for creating a "child" entity for a newly created "parent" entity in section [11.7.4 Referencing Returned Entities](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#ReferencingReturnedEntities).

Copy and adjust the example in [19.2 Referencing New Entities](https://docs.oasis-open.org/odata/odata-json-format/v4.02/csd01/odata-json-format-v4.02-csd01.html#ReferencingNewEntities).

Optional: rename section in Protocol to "Referencing New Entities", or rename section in JSON Format to "Referencing Returned Entities".

**Comment by ralfhandl** [comment]
Already in, just didn't find it 🙄

**Comment by HeikoTheissen** [comment]
Is [example 105](https://oasis-tcs.github.io/odata-specs/odata-protocol/odata-protocol.html#batchcontentid) not sufficient? It is already referenced in section 11.7.4.

**Comment by ralfhandl** [comment]
> It is already referenced in section 11.7.4.

Excellent! I was looking at CSD01, which doesn't have this reference
