### ISSUE TITLE
Allow nulls in a Collection of Entities

### ISSUE THREAD

**Issue by Hubert-Heijkers** [oasis-tcs/odata-specs#1983]
First up, at least for now (ordered collections might change my opinion on this one later;-), not trying to change the fact that a collection valued navigation property should not be nullable and therefore should not contain any nulls.

This topic is specifically for the Return Type where we specifically specify that "If the return type is a collection of entity types, the $Nullable member has no meaning and MUST NOT be specified.". For Parameters on the other hand we do not specify that limitation (albeit I don't have a case where I'd want to pass in nulls in a collection of entities).

My proposal would be to strike that limitation for Return Type referenced above, remove that sentence and remove the word 'other' from the sentence that follows, bringing it in line with the definition for Parameter.

FYI this came up as part of the discussion of #290 but by itself is unrelated as I'm not seeking to change what's allowed for a, collection valued, navigation property at this point in time.

**Comment by HeikoTheissen** [comment]
If we approve this, we must also remove https://github.com/oasis-tcs/odata-csdl-schemas/blob/fbdbc32439adbca7cc06d2ac4c928347d2296aec/lib/xml2json.js#L1733-L1743
