### ISSUE TITLE
Clarify ordering of control information for deleted entity

### ISSUE THREAD

**Issue by mikepizzo** [oasis-tcs/odata-specs#1985]
According to [payload ordering constraints](https://docs.oasis-open.org/odata/odata-json-format/v4.02/csd01/odata-json-format-v4.02-csd01.html#PayloadOrderingConstraints), `@type` immediately follows `@context`, and other control information like `@id` follows `@type`:

> - If present, the context control information MUST be the first property in the JSON object.
> - The type control information, if present, MUST appear next in the JSON object.
> - The id and etag control information MUST appear before any property, property annotation, or property control information.

However, the section on [deleted entity](https://docs.oasis-open.org/odata/odata-json-format/v4.02/csd01/odata-json-format-v4.02-csd01.html#DeletedEntity) states that `@removed` should come immediately after `@context`:

> For ordered payloads, the control information `removed` MUST immediately follow the `context` control information, if present, otherwise it MUST be the first property in the deleted entity.

and later suggests that `@id` comes immediately after `@removed`.

> For ordered payloads, the control information `id`, if present, MUST immediately follow the control information `removed`.
 
I believe that we failed to update the section on ordered payloads for `@removed`, and the text for deleted entity is just missing `@type` all together, because originally there was no reason to specify the type of a deleted entity. Later we introduced the ability to include other properties on a deleted entity, which added the requirement to include `@type` for types derived from the expected type.
 
So, if we simply neglected to include `@removed` from ordering and `@type` for deleted entity, then you could argue the expected ordering is `@context`, `@removed`, `@type`, `@id`, or perhaps `@context`, `@type`, `@removed`, `@id`.

Whether the entity is deleted is arguably more important than its type, and is more similar to OData 4.0, in which the context conveyed whether or not it was deleted, so I would argue the first makes the most sense.

Proposal:
Clarify, in payload ordering constraints, that `@removed`, if present, should come after `@context` and before `@type`, if present.
Clarify, in deleted entity, that `@type`, if present, should come after `@removed` and before `@id`.

**Comment by mikepizzo** [comment]
we should make note to consumers that 4.01 omitted that type could come between removed and id.  

other alternatives would be that type could come before removed (violates other wording) or after id (which could be problematic.)

**Comment by ralfhandl** [comment]
TC 2024-09-04: resolved as proposed with the above comment
