### ISSUE TITLE
Clarify if services should return explicitly $selected dynamic properties that are not present on the instance

### ISSUE THREAD

**Issue by mikepizzo** [oasis-tcs/odata-specs#2036]
If a dynamic property does not exist on an instance, then in the absence of a $select it is not returned.

Typically, I would expect that the payload include all of the properties that were specified in $select (unless omit-nulls/omit-default was specified), but I couldn't find anything in the docs that clearly stated the behavior of $selecting a dynamic property that didn't exist on an instance.

[ODataProtocol](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part1-protocol/odata-v4.02-csd01-part1-protocol.html#SystemQueryOptionselect) states:
The $select system query option requests that the service return only the properties, dynamic properties, actions, and functions explicitly requested by the client. The service returns the specified content, if available, along with any available expanded navigation or stream properties, and MAY return additional information.

I *did* find [this issue](https://github.com/oasis-tcs/odata-specs/issues/1446), however, which suggests that explicitly $selected dynamic properties are omitted from the payload (although I assume it would not be an error for the service to return such a dynamic property with the null value, since that is how it is cleared). If this is the expected behavior (implied by the "if available" above) then we should clarify.

Proposal: Explicitly state that $selected dynamic properties that aren't defined for a particular instance may be omitted from the response.

**Comment by HeikoTheissen** [comment]
Are there any alternatives to omitting it?
* Include it with a `null` value (I would find that misleading)
* Include only an instance annotation that explains its absence (but not the property itself)

Or is the question whether a property may be omitted _entirely_ from a collection response if it is not defined for _one_ instance contained in the collection?

**Comment by ralfhandl** [comment]
> Proposal: Explicitly state that $selected dynamic properties that aren't defined for a particular instance may be omitted from the response.

That would contradict this statement in [5.1.4 System Query Option $select](https://docs.oasis-open.org/odata/odata/v4.02/csd01/part2-url-conventions/odata-v4.02-csd01-part2-url-conventions.html#SystemQueryOptionselect):

> If the select item is not defined for the type of the resource, and that type supports dynamic properties or instance annotations, then *the property is treated as null* for all instances on which it is not defined.

In JSON "treated as null" means serialized as "`"foo": null`.

**Comment by mikepizzo** [comment]
Ah; THANK YOU!  That matches my understanding, but I was unable to find that particular statement, and issue #1446 (which is pretty old) seemed to suggest that they were omitted.

I will close with no action, unless anyone feels there is something further to clarify in the docs.
