### ISSUE TITLE
Annotate constructor/factory actions

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#297]
In [11.5.4.1 Invoking an Action](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_InvokinganAction) we define that
> Actions that create and return a single entity follow the rules for entity creation and return a Location header that contains the edit URL or read URL of the created entity.
> 

Currently there's no way for clients and generic tools to recognize such "constructor" or "factory" actions. Annotating these actions would be helpful for e.g. OpenAPI generation from $metadata.

### Proposal

Add tagging term Core.Constructor

```xml
<Term Name="Constructor" Type="Core.Tag" Nullable="false" DefaultValue="true" AppliesTo="Action">
  <Annotation Term="Core.Description" String="The annotated action constructs new entities" />
</Term>
```

Imported from [ODATA-1214](https://issues.oasis-open.org/browse/ODATA-1214)

**Comment by ralfhandl** [comment]
Both related pull requests have been merged, the only left-over is merging PR https://github.com/oasis-tcs/odata-vocabularies/pull/239 once V4.02 CS01 is published

**Comment by mikepizzo** [comment]
Closed 2024-3-4 as PRs have been created.
