### ISSUE TITLE
Generalize the use of $each

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#345]
Allow the use of `$each` between a collection-valued path and any `singleNavigationExpr`. For example,
```java
$root/SalesOrganizations/$each/ID
```
shall evaluate to a collection of primitive ID values.

(This was proposed in the TC meeting on 2022-02-10.)

Imported from [ODATA-1514](https://issues.oasis-open.org/browse/ODATA-1514)

**Comment by HeikoTheissen** [comment]
No immediate need for this. Suggest to close it without action.
