### ISSUE TITLE
Allow functions/actions to return (and take) a delta payload

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#348]
We define a delta payload that can be returned from a(n opaque) delta link, as well as other service-defined mechanisms.

However, we don't have a way to define a custom function (or action) that can return a delta payload, and there are many places where a service may want to describe the results of a custom function (or action) using a delta payload.

Similarly, one can imagine using the delta payload as a payload to a custom action.

How can users define functions/actions that can return (or take) delta payloads.

Imported from [ODATA-1527](https://issues.oasis-open.org/browse/ODATA-1527)

**Comment by mikepizzo** [comment]
This does seem useful.
Perhaps annotate the response (or parameter) to clarify that it is delta (may contain deleted entities).
Only support deep
Context URL should end in /$delta

**Comment by mikepizzo** [comment]
Resolved as proposed 2024-9-4.
