### ISSUE TITLE
clarify behavior for omitted values in PATCH and PUT

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#364]
Imported from [ODATA-1573](https://issues.oasis-open.org/browse/ODATA-1573)

**Comment by ralfhandl** [comment]
@chrisspre Could you please check whether the existing text (relevant parts italicized below) already addresses your issue?

[11.4.3 Update an Entity](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpdateanEntity) states

> The semantics of PATCH, as defined in [RFC5789], is to merge the content in the request payload with the [entity’s] current state, applying the update *only to those components specified in the request body.*

Omitted values in PATCH requests are not changed (unless as a server-defined side-effect).

> Services that support PUT MUST replace all values of structural properties with those specified in the request body. *Missing non-key, updatable structural properties not defined as dependent properties within a referential constraint MUST be set to their default values.* Omitting a non-nullable property with no service-generated or default value from a PUT request results in a 400 Bad Request error. Missing dynamic structural properties MUST be removed or set to null.

Omitted values in PUT requests are reset to their default, which typically is null.

**Comment by chrisspre** [comment]
looks good to me. Thanks

**Comment by chrisspre** [comment]
@ralfhandl do i close this, or do you and do I have to do anything first (like closing a PR?)

**Comment by mikepizzo** [comment]
Note: we closed some of the issues with null values in related entities in OData #1973.
