### ISSUE TITLE
Should be able to change type when PATCHing an entity

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#369]
In [Protocol](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpdateanEntity) we say that Entity id and entity type cannot be changed when updating an entity.

[ODATA-1472](https://issues.oasis-open.org/browse/ODATA-1472) introduces the notion of changing the type of a nested complex type, but stopped short of changing the type of an entity due to concerns that an entities type was part of its identity. 

However, updating an entity type doesn't necessarily change the identity of the entity; for example, an employee can become a manager and back.

An entities id is made up of its container plus its key properties. The allowable types that you could change an entity to is already restricted to the hierarchy of the entityset or navigation property in which the entity instance is contained, and the type of that container defines the key property, so there is no concern that changing the type of an entity will change its container nor its key property.  Therefore, an entity's identity doesn't change when you change its type.

Thus, we should allow the semantics defined in [ODATA-1472](https://issues.oasis-open.org/browse/ODATA-1472) to extend to updating the type of an entity (within the hierarchy of the collection in which it is contained).

### Proposal

Allow the semantics defined in [ODATA-1472](https://issues.oasis-open.org/browse/ODATA-1472) to extend to updating the type of an entity (within the hierarchy of the collection in which it is contained).

Imported from [ODATA-1585](https://issues.oasis-open.org/browse/ODATA-1585)

**Comment by mikepizzo** [comment]
resolved as proposed 2024-5-8
