### ISSUE TITLE
Rendering of `monospace` content depends on whether the document uses formulas

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#37]

**Comment by HeikoTheissen** [comment]
Monospaced content outside of MathJax formulas is influenced by https://github.com/oasis-tcs/odata-specs/blob/26f9b09bf20f1f783396441638f593aafd30e54b/docs/odata-data-aggregation-ext/styles/odata.css#L121-L132

This is done to ensure that keywords are always displayed in the same font, as explained [here](../lib).

The same CSS rules can also be used in other specification documents, even if they do not use MathJax.
