### ISSUE TITLE
Fix issues with Capabilities vocabulary

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#379]
There are a few typos in some of the things we added to the Capabilities vocabulary:
1) In PermissionType, "Scheme" should be of type "Edm.String" (and perhaps renamed "SchemeName") rather than Auth.SecurityScheme. We don't expect to inline the definition of the security scheme (including supported scopes, etc.)
2) OperationRestrictions should be a single Capability.OperationRestriction, not Collection(Capability.OperationRestriction).
3) For consistency, OperationRestriction should really be named OperationRestrictionType
4) We don't have a way to apply restrictions to an ActionImport.  We can target a FunctionImport with ReadRestrictions (although it would be a bit strange to have a FunctionImport with Readable=false), and Actions and Functions with OperationRestrictions, but we don't have a way to define permissions, headers, etc. associated with an ActionImport.  Everything in OperationRestrictions applies to imports *except* FilterSegmentSupported.

### Proposal

0) Define a new "SchemeName" TypeDefinition in the Auth vocabulary and use within Auth vocabulary whenever referencing a scheme.
1) In PermissionType, rename "Scheme" to "Authorization" and change type to be "Auth.SchemeName".
2) Change the type of OperationRestrictions to be Capability.OperationRestriction, not Collection(Capability.OperationRestriction).
3) Rename OperationRestriction to OperationRestrictionType
4) Remove "FunctionImport" from ReadRestrictions 

Imported from [ODATA-1318](https://issues.oasis-open.org/browse/ODATA-1318)

**Comment by ralfhandl** [comment]
Seems to have already been fixed by https://github.com/oasis-tcs/odata-vocabularies/pull/56

**Comment by mikepizzo** [comment]
Closed without action.
