### ISSUE TITLE
In should support empty literal arrays

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#396]
[ABNF] defines the inexpr as:

inExpr = RWS "in" RWS ( listExpr / commonExpr )

where listExpr is defined as:

listExpr  = OPEN BWS primitiveLiteral BWS *( COMMA BWS primitiveLiteral BWS ) CLOSE

meaning, the list must have at least one primitive literal.

Client code generating the expression may well write the open paren, loop through the elements of the array writing each into the expression, then write a close paren.  If the array is empty, this will result in an empty listExpr.

Any reason not to allow an empty listExpr and force the client code above to handle this as a special case?

### Proposal

Update listExpr in ABNF:

listExpr  = OPEN BWS [primitiveLiteral BWS *( COMMA BWS primitiveLiteral BWS )] CLOSE

Call out that this evaluates to false.
Be clear that this was added in 4.02.

Imported from [ODATA-1633](https://issues.oasis-open.org/browse/ODATA-1633)

**Comment by mikepizzo** [comment]
It appears that Ralf already fixed the ABNF 3 years ago in https://github.com/oasis-tcs/odata-abnf/pull/53, in response to https://issues.oasis-open.org/browse/ODATA-1462.

What is missing is text that says this should evaluate to false.
