### ISSUE TITLE
Clarify creation of a singleton media entity

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#398]
11.4.7.1 Create a Media Entity in [Protocol] describes how to create a media entity within a collection. It doesn't mention how to create a singleton contained media entity.

11.4.7.2 Update a Media Entity Stream says that, to update, you would submit a request to the media edit link (the editlink of the entity suffixed with /$value).

Presumably, creation of a singleton contained media entity would be done by calling PUT to the media entity link, which should return 201 created and a location header, and may set other properties of the entity, but this is not called out.

11.4.4 Upsert an Entity calls out that it's not possible to upsert a media entity, which is correct but misleading.  PUT to the media edit link replaces the media. As above, if the entity doesn't already exist it will be created with the new stream value. In either case, additional properties of the entity may be set.

### Proposal

Clarify, in section 11.4.7.1, that a singleton contained media entity is created by calling PUT to the media entity link. If the singleton was null, this should return 201 created and a location header, and may set other properties of the entity.

In 11.4.4 Upsert an Entity, clarify that, while it's not possible to upsert a media entity through a PATCH to the entity url, a PUT to the media edit link replaces the media and, if the entity doesn't already exist, results in the creation of the entity with the new stream value. In either case, additional properties of the media entity may be set when setting the stream value.

Imported from [ODATA-1638](https://issues.oasis-open.org/browse/ODATA-1638)

**Comment by mikepizzo** [comment]
Trying to recall what we intended by "In either case, additional properties of the media entity may be set when setting the stream value."

Did we mean that the *service* may set additional properties of the media entity, or that the client could specify additional properties as part of the update. If you PUT to the media entity link, it's unclear to me how you would specify additional properties, so I assume we meant the former (that the service may set additional properties).

**Comment by ralfhandl** [comment]
I'd assume that

> the _service_ may set additional properties of the media entity

for example by interpreting the [`Slug` header](https://www.rfc-editor.org/rfc/rfc5023.html#section-9.7), or by setting [calculated properties](https://cap.cloud.sap/docs/cds/common#aspect-managed).
