### ISSUE TITLE
Keep sources away from folder holding generated files

### ISSUE THREAD

**Issue by GeraldKrause** [oasis-tcs/odata-specs#41]
`docs` is the target folder for the generated files and has a structure that is used by subsequent tool chains.

Currently, `docs` also contains `styles` folders for each generated document. The style files are _original sources_. Hence, it is not easily possible to have a `make clean`  that simply removes the generated `docs` folder.

Suggestion is to keep the styles files in another folder separate from `docs`

**Comment by HeikoTheissen** [comment]
Do we strive for the same `styles` files for all specification documents?
