### ISSUE TITLE
number.js does not warn about incorrect section number references

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#80]
Section number references `[subsection ##SubsectionHeading]` to a non-existing heading do not produce warning messages in the build script.

**Comment by HeikoTheissen** [comment]
I get
```
❌ odata-csdl xml
odata-csdl/0 frontmatter.md(101): Undefined link ##SubsectionHeading
```

**Comment by HeikoTheissen** [comment]
> When I used stand-ins like `[section ##1.2.3]` I didn’t get warnings

This introduces a new counter named "1" and leads to
```
[section 1.2.3]
```

**Comment by ralfhandl** [comment]
Is that a bug or a feature? When would I use this feature?

I found the current behaviour surprising, and would have preferred a warning in the log.

If you want to keep it how it works now, just close this issue.

Thanks in advance!

**Comment by HeikoTheissen** [comment]
> Is that a bug or a feature? When would I use this feature?

It is a feature that links are generated by `##someabbrev` and referenced by `[... ##someabbrev]`. But I have now allowed dots in `abbrev` so that `[section ##1.2.3]` gives a warning.
