### ISSUE TITLE
Required check not set if build workflow pushes changes

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-specs#91]
Pull requests require the build check to pass. 

If the build workflow makes changes to `docs` and pushes them, the check is not set even though the build step succeeds.

The push from the build workflow does not trigger a new workflow run as explained here: [Triggering a workflow from a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

Options:
- Use a GitHub App installation access token or a personal access token instead of GITHUB_TOKEN to trigger events that require a token. And make sure we don’t cause an endless chain of triggers. 
- Figure out how to have the check reported as passed despite the push because we know that one build run is sufficient.

**Comment by HeikoTheissen** [comment]
> The push from the build workflow does not trigger a new workflow run as explained here: [Triggering a workflow from a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

Then why does it work in the https://github.com/SAP/odata-vocabularies repository?

**Comment by ralfhandl** [comment]
Good question! How do the workflows differ, and how the repository settings?

**Comment by HeikoTheissen** [comment]
> Good question! How do the workflows differ, and how the repository settings?

I cannot spot a relevant difference between the "Settings" of these two repositories.

**Comment by ralfhandl** [comment]
Workaround:
- run build without committing and pushing
- just check if there were changes and return an error

```bash
git diff --exit-code docs
```

**Comment by HeikoTheissen** [comment]
> Workaround:

#132

**Comment by ralfhandl** [comment]
Just spotted the difference: https://github.com/SAP/odata-vocabularies does not have any required status checks, we rely on the maintainers to merge only PRs whose build ran green.
